services:
  - type: web
    name: mulasense-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn MulaSense.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mulasense-db
          property: connectionString

databases:
  - name: mulasense-db
    databaseName: mulasense
    user: mulasense_user
